name: Publish Docker image
on:
  release:
    branch: main
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      -
        name: Prepare
        id: prep
        run: |
          GHCR_IMAGE=ghcr.io/${{ github.repository_owner }}/helm
          VERSION=latest

          TAGS="${GHCR_IMAGE}:${VERSION}"

          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            TAGS="${TAGS},${GHCR_IMAGE}:${VERSION}"
          fi


          echo ::set-output name=version::${VERSION}
          echo ::set-output name=ghcr_image::${GHCR_IMAGE}
          echo ::set-output name=tags::${TAGS}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.prep.outputs.tags }}
      -
        name: Check manifest
        run: |
          docker buildx imagetools inspect ${{ steps.prep.outputs.ghcr_image }}:${{ steps.prep.outputs.version }}