name: Test scripts on push
on:
  push:
    branch: main
jobs:
  test_scripts:
    name: Test scripts
    runs-on: ubuntu-latest
    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1.0.1
        with:
          bats-version: 1.2.1

      - name: Check out code
        uses: actions/checkout@v1

      - name: Test
        run: bats -r .