name: Test scripts on push
on:
  push:
    branches: 
      - main
jobs:
  test_scripts:
    name: Test scripts
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - 
        # this is necessary to prevent desynch state when triggered by previous workflow
        name: Sync git repository
        run: git checkout HEAD^
      - 
        name: Run Bats Tests
        uses: ffurrer2/bats-action@v1
        with:
          args: ./test/checkHelmVersion.bats