name: Test scripts on push
on:
  push:
    branch: main
jobs:
  test_scripts:
    name: Test scripts
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out code
        uses: actions/checkout@v1
      - 
        name: Run Bats Tests
        uses: ffurrer2/bats-action@v1
        with:
          args: ./test/checkHelmVersion.bats